# Generated by Django 3.2.6 on 2021-08-18 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='lien',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
