# Generated by Django 3.2.6 on 2021-08-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_lien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='logo',
            new_name='image',
        ),
    ]
