# Generated by Django 3.2.6 on 2021-08-18 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technologies',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ph_tech'),
            preserve_default=False,
        ),
    ]
