# Generated by Django 3.2.6 on 2021-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_auto_20210818_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='logo',
            field=models.ImageField(upload_to='technologies/static/technologies/images/'),
        ),
    ]
